# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.elicitation_result import ElicitationResult
from ..types.event_response import EventResponse
from ..types.field import Field
from ..types.field_bid import FieldBid
from .raw_client import AsyncRawElicitationsClient, RawElicitationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ElicitationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawElicitationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawElicitationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawElicitationsClient
        """
        return self._raw_client

    def create(
        self,
        *,
        idempotency_key: str,
        fields: typing.Sequence[Field],
        project_name: str,
        summary: str,
        task_id: str,
        attachments: typing.Optional[typing.Sequence[str]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        recommendation: typing.Optional[typing.Sequence[FieldBid]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the answers.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        fields : typing.Sequence[Field]

        project_name : str

        summary : str
            Human-readable summary of what's needed

        task_id : str
            Target task — create one via POST /tasks first

        attachments : typing.Optional[typing.Sequence[str]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]

        key_value_context : typing.Optional[typing.Dict[str, str]]

        recommendation : typing.Optional[typing.Sequence[FieldBid]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        from pumpup import Field_DateField, PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.elicitations.create(
            idempotency_key="Idempotency-Key",
            fields=[
                Field_DateField(
                    id="id",
                    label="label",
                    required=True,
                )
            ],
            project_name="projectName",
            summary="Need additional details on the incident",
            task_id="taskId",
        )
        """
        _response = self._raw_client.create(
            idempotency_key=idempotency_key,
            fields=fields,
            project_name=project_name,
            summary=summary,
            task_id=task_id,
            attachments=attachments,
            external_trace_id=external_trace_id,
            key_value_context=key_value_context,
            recommendation=recommendation,
            request_options=request_options,
        )
        return _response.data

    def get_result(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[ElicitationResult]:
        """
        200 with the provided fields once a human has answered; 204 while still pending.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[ElicitationResult]
            OK

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.elicitations.get_result(
            id="id",
        )
        """
        _response = self._raw_client.get_result(id, request_options=request_options)
        return _response.data


class AsyncElicitationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawElicitationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawElicitationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawElicitationsClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        idempotency_key: str,
        fields: typing.Sequence[Field],
        project_name: str,
        summary: str,
        task_id: str,
        attachments: typing.Optional[typing.Sequence[str]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        recommendation: typing.Optional[typing.Sequence[FieldBid]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the answers.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        fields : typing.Sequence[Field]

        project_name : str

        summary : str
            Human-readable summary of what's needed

        task_id : str
            Target task — create one via POST /tasks first

        attachments : typing.Optional[typing.Sequence[str]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]

        key_value_context : typing.Optional[typing.Dict[str, str]]

        recommendation : typing.Optional[typing.Sequence[FieldBid]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp, Field_DateField

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.elicitations.create(
                idempotency_key="Idempotency-Key",
                fields=[
                    Field_DateField(
                        id="id",
                        label="label",
                        required=True,
                    )
                ],
                project_name="projectName",
                summary="Need additional details on the incident",
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            idempotency_key=idempotency_key,
            fields=fields,
            project_name=project_name,
            summary=summary,
            task_id=task_id,
            attachments=attachments,
            external_trace_id=external_trace_id,
            key_value_context=key_value_context,
            recommendation=recommendation,
            request_options=request_options,
        )
        return _response.data

    async def get_result(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[ElicitationResult]:
        """
        200 with the provided fields once a human has answered; 204 while still pending.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[ElicitationResult]
            OK

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.elicitations.get_result(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_result(id, request_options=request_options)
        return _response.data
