# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError as core_api_error_ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..types.api_error import ApiError as types_api_error_ApiError
from ..types.attachment import Attachment
from ..types.elicitation_result import ElicitationResult
from ..types.error_response import ErrorResponse
from ..types.event_response import EventResponse
from ..types.field_bid import FieldBid
from ..types.metadata_patch_dto import MetadataPatchDto
from ..types.object_id import ObjectId
from .types.create_elicitation_request_fields_item import CreateElicitationRequestFieldsItem
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawElicitationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        idempotency_key: str,
        fields: typing.Sequence[CreateElicitationRequestFieldsItem],
        project_name: str,
        summary: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        attachments: typing.Optional[typing.Sequence[ObjectId]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        recommendation: typing.Optional[typing.Sequence[FieldBid]] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EventResponse]:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the answers.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        fields : typing.Sequence[CreateElicitationRequestFieldsItem]

        project_name : str

        summary : str
            Human-readable summary of what's needed

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        attachments : typing.Optional[typing.Sequence[ObjectId]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]

        key_value_context : typing.Optional[typing.Dict[str, str]]

        metadata_patch : typing.Optional[MetadataPatchDto]

        recommendation : typing.Optional[typing.Sequence[FieldBid]]

        task_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EventResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/elicitation-requests",
            method="POST",
            json={
                "addAttachments": convert_and_respect_annotation_metadata(
                    object_=add_attachments, annotation=typing.Sequence[Attachment], direction="write"
                ),
                "attachments": convert_and_respect_annotation_metadata(
                    object_=attachments, annotation=typing.Sequence[ObjectId], direction="write"
                ),
                "externalTraceId": external_trace_id,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[CreateElicitationRequestFieldsItem], direction="write"
                ),
                "keyValueContext": key_value_context,
                "metadataPatch": convert_and_respect_annotation_metadata(
                    object_=metadata_patch, annotation=MetadataPatchDto, direction="write"
                ),
                "projectName": project_name,
                "recommendation": convert_and_respect_annotation_metadata(
                    object_=recommendation, annotation=typing.Sequence[FieldBid], direction="write"
                ),
                "summary": summary,
                "taskId": task_id,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EventResponse,
                    parse_obj_as(
                        type_=EventResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )

    def get_result(
        self, id: ObjectId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ElicitationResult]:
        """
        200 with the provided fields once a human has answered; 204 while still pending.

        Parameters
        ----------
        id : ObjectId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ElicitationResult]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/elicitation-requests/{encode_path_param(convert_and_respect_annotation_metadata(object_=id, annotation=ObjectId, direction='write'))}/result",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ElicitationResult,
                    parse_obj_as(
                        type_=ElicitationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )


class AsyncRawElicitationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        idempotency_key: str,
        fields: typing.Sequence[CreateElicitationRequestFieldsItem],
        project_name: str,
        summary: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        attachments: typing.Optional[typing.Sequence[ObjectId]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        recommendation: typing.Optional[typing.Sequence[FieldBid]] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EventResponse]:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the answers.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        fields : typing.Sequence[CreateElicitationRequestFieldsItem]

        project_name : str

        summary : str
            Human-readable summary of what's needed

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        attachments : typing.Optional[typing.Sequence[ObjectId]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]

        key_value_context : typing.Optional[typing.Dict[str, str]]

        metadata_patch : typing.Optional[MetadataPatchDto]

        recommendation : typing.Optional[typing.Sequence[FieldBid]]

        task_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EventResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/elicitation-requests",
            method="POST",
            json={
                "addAttachments": convert_and_respect_annotation_metadata(
                    object_=add_attachments, annotation=typing.Sequence[Attachment], direction="write"
                ),
                "attachments": convert_and_respect_annotation_metadata(
                    object_=attachments, annotation=typing.Sequence[ObjectId], direction="write"
                ),
                "externalTraceId": external_trace_id,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[CreateElicitationRequestFieldsItem], direction="write"
                ),
                "keyValueContext": key_value_context,
                "metadataPatch": convert_and_respect_annotation_metadata(
                    object_=metadata_patch, annotation=MetadataPatchDto, direction="write"
                ),
                "projectName": project_name,
                "recommendation": convert_and_respect_annotation_metadata(
                    object_=recommendation, annotation=typing.Sequence[FieldBid], direction="write"
                ),
                "summary": summary,
                "taskId": task_id,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EventResponse,
                    parse_obj_as(
                        type_=EventResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )

    async def get_result(
        self, id: ObjectId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ElicitationResult]:
        """
        200 with the provided fields once a human has answered; 204 while still pending.

        Parameters
        ----------
        id : ObjectId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ElicitationResult]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/elicitation-requests/{encode_path_param(convert_and_respect_annotation_metadata(object_=id, annotation=ObjectId, direction='write'))}/result",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ElicitationResult,
                    parse_obj_as(
                        type_=ElicitationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )
