# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.attachment import Attachment
from ..types.event_response import EventResponse
from ..types.metadata_patch_dto import MetadataPatchDto
from .raw_client import AsyncRawEventsClient, RawEventsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def agent_action(
        self,
        *,
        idempotency_key: str,
        description: str,
        project_name: str,
        task_id: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        detail: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        transitions_to: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        description : str
            What the agent did

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        detail : typing.Optional[typing.Dict[str, typing.Any]]

        external_trace_id : typing.Optional[str]

        metadata_patch : typing.Optional[MetadataPatchDto]

        transitions_to : typing.Optional[str]
            State to transition the task into; must be a declared transition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.events.agent_action(
            idempotency_key="Idempotency-Key",
            description="Auto-classified claim as low-risk",
            project_name="projectName",
            task_id="taskId",
        )
        """
        _response = self._raw_client.agent_action(
            idempotency_key=idempotency_key,
            description=description,
            project_name=project_name,
            task_id=task_id,
            add_attachments=add_attachments,
            detail=detail,
            external_trace_id=external_trace_id,
            metadata_patch=metadata_patch,
            transitions_to=transitions_to,
            request_options=request_options,
        )
        return _response.data

    def exception(
        self,
        *,
        idempotency_key: str,
        message: str,
        project_name: str,
        task_id: str,
        detail: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        transitions_to: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        message : str
            What went wrong

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        detail : typing.Optional[typing.Dict[str, typing.Any]]

        external_trace_id : typing.Optional[str]

        transitions_to : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.events.exception(
            idempotency_key="Idempotency-Key",
            message="OCR failed on uploaded document",
            project_name="projectName",
            task_id="taskId",
        )
        """
        _response = self._raw_client.exception(
            idempotency_key=idempotency_key,
            message=message,
            project_name=project_name,
            task_id=task_id,
            detail=detail,
            external_trace_id=external_trace_id,
            transitions_to=transitions_to,
            request_options=request_options,
        )
        return _response.data

    def note(
        self,
        *,
        idempotency_key: str,
        message: str,
        project_name: str,
        task_id: str,
        external_trace_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        message : str
            The annotation text

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        external_trace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.events.note(
            idempotency_key="Idempotency-Key",
            message="Customer called to confirm bank details",
            project_name="projectName",
            task_id="taskId",
        )
        """
        _response = self._raw_client.note(
            idempotency_key=idempotency_key,
            message=message,
            project_name=project_name,
            task_id=task_id,
            external_trace_id=external_trace_id,
            request_options=request_options,
        )
        return _response.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def agent_action(
        self,
        *,
        idempotency_key: str,
        description: str,
        project_name: str,
        task_id: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        detail: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        transitions_to: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        description : str
            What the agent did

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        detail : typing.Optional[typing.Dict[str, typing.Any]]

        external_trace_id : typing.Optional[str]

        metadata_patch : typing.Optional[MetadataPatchDto]

        transitions_to : typing.Optional[str]
            State to transition the task into; must be a declared transition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.agent_action(
                idempotency_key="Idempotency-Key",
                description="Auto-classified claim as low-risk",
                project_name="projectName",
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.agent_action(
            idempotency_key=idempotency_key,
            description=description,
            project_name=project_name,
            task_id=task_id,
            add_attachments=add_attachments,
            detail=detail,
            external_trace_id=external_trace_id,
            metadata_patch=metadata_patch,
            transitions_to=transitions_to,
            request_options=request_options,
        )
        return _response.data

    async def exception(
        self,
        *,
        idempotency_key: str,
        message: str,
        project_name: str,
        task_id: str,
        detail: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        transitions_to: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        message : str
            What went wrong

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        detail : typing.Optional[typing.Dict[str, typing.Any]]

        external_trace_id : typing.Optional[str]

        transitions_to : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.exception(
                idempotency_key="Idempotency-Key",
                message="OCR failed on uploaded document",
                project_name="projectName",
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.exception(
            idempotency_key=idempotency_key,
            message=message,
            project_name=project_name,
            task_id=task_id,
            detail=detail,
            external_trace_id=external_trace_id,
            transitions_to=transitions_to,
            request_options=request_options,
        )
        return _response.data

    async def note(
        self,
        *,
        idempotency_key: str,
        message: str,
        project_name: str,
        task_id: str,
        external_trace_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        message : str
            The annotation text

        project_name : str

        task_id : str
            Target task — create one via POST /tasks first

        external_trace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.note(
                idempotency_key="Idempotency-Key",
                message="Customer called to confirm bank details",
                project_name="projectName",
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.note(
            idempotency_key=idempotency_key,
            message=message,
            project_name=project_name,
            task_id=task_id,
            external_trace_id=external_trace_id,
            request_options=request_options,
        )
        return _response.data
