# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.project_list_response import ProjectListResponse
from ..types.project_response import ProjectResponse
from .raw_client import AsyncRawProjectsClient, RawProjectsClient


class ProjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProjectsClient
        """
        return self._raw_client

    def list(
        self, *, name: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ProjectListResponse:
        """
        Optionally filter by a case-insensitive substring of the display name or slug; the response carries the slug to reference on ingest.

        Parameters
        ----------
        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectListResponse
            OK

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.projects.list()
        """
        _response = self._raw_client.list(name=name, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ProjectResponse:
        """
        Includes the declared step graph.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectResponse
            OK

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.projects.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncProjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProjectsClient
        """
        return self._raw_client

    async def list(
        self, *, name: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ProjectListResponse:
        """
        Optionally filter by a case-insensitive substring of the display name or slug; the response carries the slug to reference on ingest.

        Parameters
        ----------
        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectListResponse
            OK

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.projects.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(name=name, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ProjectResponse:
        """
        Includes the declared step graph.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectResponse
            OK

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.projects.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
