# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.resolved_upload import ResolvedUpload
from ..types.upload_ref import UploadRef
from .raw_client import AsyncRawUploadsClient, RawUploadsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UploadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUploadsClient
        """
        return self._raw_client

    def upload(self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None) -> UploadRef:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadRef
            Created

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.uploads.upload()
        """
        _response = self._raw_client.upload(file=file, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ResolvedUpload:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedUpload
            OK

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.uploads.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncUploadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUploadsClient
        """
        return self._raw_client

    async def upload(self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None) -> UploadRef:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadRef
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.uploads.upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(file=file, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ResolvedUpload:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedUpload
            OK

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.uploads.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
