# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_error import ApiError
    from .approval_recommendation import ApprovalRecommendation
    from .approval_result import ApprovalResult
    from .attachment import Attachment
    from .authority_snapshot import AuthoritySnapshot
    from .date_field import DateField
    from .date_time import DateTime
    from .elicitation_result import ElicitationResult
    from .error_response import ErrorResponse
    from .event_response import EventResponse
    from .field import (
        Field,
        Field_DateField,
        Field_DateTime,
        Field_Multiselect,
        Field_Number,
        Field_Select,
        Field_Slider,
        Field_Switch,
        Field_Text,
        Field_TextArea,
        Field_Time,
    )
    from .field_bid import FieldBid
    from .metadata_patch_dto import MetadataPatchDto
    from .multiselect import Multiselect
    from .number import Number
    from .object_id import ObjectId
    from .open_request_dto import OpenRequestDto
    from .open_request_dto_event_type import OpenRequestDtoEventType
    from .outcome import Outcome
    from .outcome_type import OutcomeType
    from .project_list_response import ProjectListResponse
    from .project_response import ProjectResponse
    from .resolved_upload import ResolvedUpload
    from .select import Select
    from .slider import Slider
    from .step import Step
    from .step_owner import StepOwner
    from .steps import Steps
    from .steps_state_schemas import StepsStateSchemas
    from .switch import Switch
    from .task_detail_response import TaskDetailResponse
    from .task_list_response import TaskListResponse
    from .task_response import TaskResponse
    from .task_response_status import TaskResponseStatus
    from .text import Text
    from .text_area import TextArea
    from .text_format import TextFormat
    from .time import Time
    from .upload_ref import UploadRef
    from .upload_ref_status import UploadRefStatus
_dynamic_imports: typing.Dict[str, str] = {
    "ApiError": ".api_error",
    "ApprovalRecommendation": ".approval_recommendation",
    "ApprovalResult": ".approval_result",
    "Attachment": ".attachment",
    "AuthoritySnapshot": ".authority_snapshot",
    "DateField": ".date_field",
    "DateTime": ".date_time",
    "ElicitationResult": ".elicitation_result",
    "ErrorResponse": ".error_response",
    "EventResponse": ".event_response",
    "Field": ".field",
    "FieldBid": ".field_bid",
    "Field_DateField": ".field",
    "Field_DateTime": ".field",
    "Field_Multiselect": ".field",
    "Field_Number": ".field",
    "Field_Select": ".field",
    "Field_Slider": ".field",
    "Field_Switch": ".field",
    "Field_Text": ".field",
    "Field_TextArea": ".field",
    "Field_Time": ".field",
    "MetadataPatchDto": ".metadata_patch_dto",
    "Multiselect": ".multiselect",
    "Number": ".number",
    "ObjectId": ".object_id",
    "OpenRequestDto": ".open_request_dto",
    "OpenRequestDtoEventType": ".open_request_dto_event_type",
    "Outcome": ".outcome",
    "OutcomeType": ".outcome_type",
    "ProjectListResponse": ".project_list_response",
    "ProjectResponse": ".project_response",
    "ResolvedUpload": ".resolved_upload",
    "Select": ".select",
    "Slider": ".slider",
    "Step": ".step",
    "StepOwner": ".step_owner",
    "Steps": ".steps",
    "StepsStateSchemas": ".steps_state_schemas",
    "Switch": ".switch",
    "TaskDetailResponse": ".task_detail_response",
    "TaskListResponse": ".task_list_response",
    "TaskResponse": ".task_response",
    "TaskResponseStatus": ".task_response_status",
    "Text": ".text",
    "TextArea": ".text_area",
    "TextFormat": ".text_format",
    "Time": ".time",
    "UploadRef": ".upload_ref",
    "UploadRefStatus": ".upload_ref_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiError",
    "ApprovalRecommendation",
    "ApprovalResult",
    "Attachment",
    "AuthoritySnapshot",
    "DateField",
    "DateTime",
    "ElicitationResult",
    "ErrorResponse",
    "EventResponse",
    "Field",
    "FieldBid",
    "Field_DateField",
    "Field_DateTime",
    "Field_Multiselect",
    "Field_Number",
    "Field_Select",
    "Field_Slider",
    "Field_Switch",
    "Field_Text",
    "Field_TextArea",
    "Field_Time",
    "MetadataPatchDto",
    "Multiselect",
    "Number",
    "ObjectId",
    "OpenRequestDto",
    "OpenRequestDtoEventType",
    "Outcome",
    "OutcomeType",
    "ProjectListResponse",
    "ProjectResponse",
    "ResolvedUpload",
    "Select",
    "Slider",
    "Step",
    "StepOwner",
    "Steps",
    "StepsStateSchemas",
    "Switch",
    "TaskDetailResponse",
    "TaskListResponse",
    "TaskResponse",
    "TaskResponseStatus",
    "Text",
    "TextArea",
    "TextFormat",
    "Time",
    "UploadRef",
    "UploadRefStatus",
]
