# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action import Action
    from .action_detail import ActionDetail
    from .api_error import ApiError
    from .approval_decided import ApprovalDecided
    from .approval_recommendation import ApprovalRecommendation
    from .approval_requested import ApprovalRequested
    from .approval_result import ApprovalResult
    from .assignment import Assignment
    from .attachment import Attachment
    from .authority_snapshot import AuthoritySnapshot
    from .date_field import DateField
    from .date_time import DateTime
    from .document import Document
    from .elicitation_provided import ElicitationProvided
    from .elicitation_requested import ElicitationRequested
    from .elicitation_requested_fields_item import ElicitationRequestedFieldsItem
    from .elicitation_result import ElicitationResult
    from .error_response import ErrorResponse
    from .event_response import EventResponse
    from .event_row import EventRow
    from .event_row_event_type import EventRowEventType
    from .event_row_owner import EventRowOwner
    from .event_row_source import EventRowSource
    from .exception_raised import ExceptionRaised
    from .exception_raised_detail import ExceptionRaisedDetail
    from .field import (
        Field,
        Field_DateField,
        Field_DateTime,
        Field_Multiselect,
        Field_Number,
        Field_Select,
        Field_Slider,
        Field_Switch,
        Field_Text,
        Field_TextArea,
        Field_Time,
    )
    from .field_bid import FieldBid
    from .metadata_patch import MetadataPatch
    from .metadata_patch_dto import MetadataPatchDto
    from .multiselect import Multiselect
    from .note import Note
    from .number import Number
    from .open_request_dto import OpenRequestDto
    from .open_request_dto_event_type import OpenRequestDtoEventType
    from .outcome import Outcome
    from .outcome_type import OutcomeType
    from .payload import (
        Payload,
        Payload_Action,
        Payload_ApprovalDecided,
        Payload_ApprovalRequested,
        Payload_Assignment,
        Payload_ElicitationProvided,
        Payload_ElicitationRequested,
        Payload_ExceptionRaised,
        Payload_Note,
        Payload_TaskClosed,
        Payload_TaskCreated,
        Payload_Timeout,
    )
    from .project_list_response import ProjectListResponse
    from .project_response import ProjectResponse
    from .resolved_upload import ResolvedUpload
    from .select import Select
    from .slider import Slider
    from .step import Step
    from .step_owner import StepOwner
    from .steps import Steps
    from .switch import Switch
    from .task_closed import TaskClosed
    from .task_created import TaskCreated
    from .task_detail_response import TaskDetailResponse
    from .task_events_response import TaskEventsResponse
    from .task_list_response import TaskListResponse
    from .task_response import TaskResponse
    from .task_response_status import TaskResponseStatus
    from .text import Text
    from .text_area import TextArea
    from .text_format import TextFormat
    from .time import Time
    from .timeout import Timeout
    from .upload_ref import UploadRef
    from .upload_ref_status import UploadRefStatus
_dynamic_imports: typing.Dict[str, str] = {
    "Action": ".action",
    "ActionDetail": ".action_detail",
    "ApiError": ".api_error",
    "ApprovalDecided": ".approval_decided",
    "ApprovalRecommendation": ".approval_recommendation",
    "ApprovalRequested": ".approval_requested",
    "ApprovalResult": ".approval_result",
    "Assignment": ".assignment",
    "Attachment": ".attachment",
    "AuthoritySnapshot": ".authority_snapshot",
    "DateField": ".date_field",
    "DateTime": ".date_time",
    "Document": ".document",
    "ElicitationProvided": ".elicitation_provided",
    "ElicitationRequested": ".elicitation_requested",
    "ElicitationRequestedFieldsItem": ".elicitation_requested_fields_item",
    "ElicitationResult": ".elicitation_result",
    "ErrorResponse": ".error_response",
    "EventResponse": ".event_response",
    "EventRow": ".event_row",
    "EventRowEventType": ".event_row_event_type",
    "EventRowOwner": ".event_row_owner",
    "EventRowSource": ".event_row_source",
    "ExceptionRaised": ".exception_raised",
    "ExceptionRaisedDetail": ".exception_raised_detail",
    "Field": ".field",
    "FieldBid": ".field_bid",
    "Field_DateField": ".field",
    "Field_DateTime": ".field",
    "Field_Multiselect": ".field",
    "Field_Number": ".field",
    "Field_Select": ".field",
    "Field_Slider": ".field",
    "Field_Switch": ".field",
    "Field_Text": ".field",
    "Field_TextArea": ".field",
    "Field_Time": ".field",
    "MetadataPatch": ".metadata_patch",
    "MetadataPatchDto": ".metadata_patch_dto",
    "Multiselect": ".multiselect",
    "Note": ".note",
    "Number": ".number",
    "OpenRequestDto": ".open_request_dto",
    "OpenRequestDtoEventType": ".open_request_dto_event_type",
    "Outcome": ".outcome",
    "OutcomeType": ".outcome_type",
    "Payload": ".payload",
    "Payload_Action": ".payload",
    "Payload_ApprovalDecided": ".payload",
    "Payload_ApprovalRequested": ".payload",
    "Payload_Assignment": ".payload",
    "Payload_ElicitationProvided": ".payload",
    "Payload_ElicitationRequested": ".payload",
    "Payload_ExceptionRaised": ".payload",
    "Payload_Note": ".payload",
    "Payload_TaskClosed": ".payload",
    "Payload_TaskCreated": ".payload",
    "Payload_Timeout": ".payload",
    "ProjectListResponse": ".project_list_response",
    "ProjectResponse": ".project_response",
    "ResolvedUpload": ".resolved_upload",
    "Select": ".select",
    "Slider": ".slider",
    "Step": ".step",
    "StepOwner": ".step_owner",
    "Steps": ".steps",
    "Switch": ".switch",
    "TaskClosed": ".task_closed",
    "TaskCreated": ".task_created",
    "TaskDetailResponse": ".task_detail_response",
    "TaskEventsResponse": ".task_events_response",
    "TaskListResponse": ".task_list_response",
    "TaskResponse": ".task_response",
    "TaskResponseStatus": ".task_response_status",
    "Text": ".text",
    "TextArea": ".text_area",
    "TextFormat": ".text_format",
    "Time": ".time",
    "Timeout": ".timeout",
    "UploadRef": ".upload_ref",
    "UploadRefStatus": ".upload_ref_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Action",
    "ActionDetail",
    "ApiError",
    "ApprovalDecided",
    "ApprovalRecommendation",
    "ApprovalRequested",
    "ApprovalResult",
    "Assignment",
    "Attachment",
    "AuthoritySnapshot",
    "DateField",
    "DateTime",
    "Document",
    "ElicitationProvided",
    "ElicitationRequested",
    "ElicitationRequestedFieldsItem",
    "ElicitationResult",
    "ErrorResponse",
    "EventResponse",
    "EventRow",
    "EventRowEventType",
    "EventRowOwner",
    "EventRowSource",
    "ExceptionRaised",
    "ExceptionRaisedDetail",
    "Field",
    "FieldBid",
    "Field_DateField",
    "Field_DateTime",
    "Field_Multiselect",
    "Field_Number",
    "Field_Select",
    "Field_Slider",
    "Field_Switch",
    "Field_Text",
    "Field_TextArea",
    "Field_Time",
    "MetadataPatch",
    "MetadataPatchDto",
    "Multiselect",
    "Note",
    "Number",
    "OpenRequestDto",
    "OpenRequestDtoEventType",
    "Outcome",
    "OutcomeType",
    "Payload",
    "Payload_Action",
    "Payload_ApprovalDecided",
    "Payload_ApprovalRequested",
    "Payload_Assignment",
    "Payload_ElicitationProvided",
    "Payload_ElicitationRequested",
    "Payload_ExceptionRaised",
    "Payload_Note",
    "Payload_TaskClosed",
    "Payload_TaskCreated",
    "Payload_Timeout",
    "ProjectListResponse",
    "ProjectResponse",
    "ResolvedUpload",
    "Select",
    "Slider",
    "Step",
    "StepOwner",
    "Steps",
    "Switch",
    "TaskClosed",
    "TaskCreated",
    "TaskDetailResponse",
    "TaskEventsResponse",
    "TaskListResponse",
    "TaskResponse",
    "TaskResponseStatus",
    "Text",
    "TextArea",
    "TextFormat",
    "Time",
    "Timeout",
    "UploadRef",
    "UploadRefStatus",
]
