# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .outcome import Outcome


class ApprovalRecommendation(UniversalBaseModel):
    confidence: typing.Optional[float] = None
    outcome: Outcome
    rationale: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
