# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .approval_recommendation import ApprovalRecommendation
from .authority_snapshot import AuthoritySnapshot
from .outcome import Outcome


class ApprovalDecided(UniversalBaseModel):
    authority: typing.Optional[AuthoritySnapshot] = None
    outcome: Outcome
    recommendation_snapshot: typing_extensions.Annotated[
        typing.Optional[ApprovalRecommendation],
        FieldMetadata(alias="recommendationSnapshot"),
        pydantic.Field(alias="recommendationSnapshot", default=None),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
