# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .approval_recommendation import ApprovalRecommendation


class ApprovalRequested(UniversalBaseModel):
    attachments: typing.Optional[typing.List[str]] = None
    key_value_context: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="keyValueContext"),
        pydantic.Field(alias="keyValueContext"),
    ] = None
    recommendation: typing.Optional[ApprovalRecommendation] = None
    summary: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
