# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class Assignment(UniversalBaseModel):
    assignee_id: typing_extensions.Annotated[str, FieldMetadata(alias="assigneeId"), pydantic.Field(alias="assigneeId")]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
