# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class Attachment(UniversalBaseModel):
    label: str
    upload_id: typing_extensions.Annotated[str, FieldMetadata(alias="uploadId"), pydantic.Field(alias="uploadId")]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
