# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class ElicitationProvided(UniversalBaseModel):
    answered_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="answeredBy"), pydantic.Field(alias="answeredBy", default=None)
    ]
    answers: typing.Optional[typing.Dict[str, typing.Any]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
