# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .elicitation_requested_fields_item import ElicitationRequestedFieldsItem
from .field_bid import FieldBid


class ElicitationRequested(UniversalBaseModel):
    attachments: typing.Optional[typing.List[str]] = None
    fields: typing.Optional[typing.List[ElicitationRequestedFieldsItem]] = None
    key_value_context: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="keyValueContext"),
        pydantic.Field(alias="keyValueContext", default=None),
    ]
    recommendation: typing.Optional[typing.List[FieldBid]] = None
    summary: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
