# This file was auto-generated by Fern from our API Definition.

import typing

from .date_field import DateField
from .date_time import DateTime
from .multiselect import Multiselect
from .number import Number
from .select import Select
from .slider import Slider
from .switch import Switch
from .text import Text
from .text_area import TextArea
from .time import Time

ElicitationRequestedFieldsItem = typing.Union[
    DateField, DateTime, Multiselect, Number, Select, Slider, Switch, Text, TextArea, Time
]
