# This file was auto-generated by Fern from our API Definition.

import typing

EventRowEventType = typing.Union[
    typing.Literal[
        "APPROVAL_REQUESTED",
        "APPROVAL_DECIDED",
        "ELICITATION_REQUESTED",
        "ELICITATION_PROVIDED",
        "ACTION",
        "EXCEPTION",
        "NOTE",
        "TIMEOUT",
        "ASSIGNMENT",
        "TASK_CREATED",
        "TASK_CLOSED",
    ],
    typing.Any,
]
