# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .event_row_event_type import EventRowEventType
from .event_row_owner import EventRowOwner
from .event_row_source import EventRowSource
from .payload import Payload


class EventRow(UniversalBaseModel):
    event_type: typing_extensions.Annotated[
        EventRowEventType, FieldMetadata(alias="eventType"), pydantic.Field(alias="eventType")
    ]
    external_trace_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalTraceId"), pydantic.Field(alias="externalTraceId")
    ] = None
    id: str
    in_response_to: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="inResponseTo"), pydantic.Field(alias="inResponseTo")
    ] = None
    owner: EventRowOwner
    payload: Payload
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId"), pydantic.Field(alias="projectId")]
    source: EventRowSource
    task_id: typing_extensions.Annotated[str, FieldMetadata(alias="taskId"), pydantic.Field(alias="taskId")]
    timestamp: dt.datetime
    transition_from: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="transitionFrom"), pydantic.Field(alias="transitionFrom")
    ] = None
    transition_to: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="transitionTo"), pydantic.Field(alias="transitionTo")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
