# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .exception_raised_detail import ExceptionRaisedDetail


class ExceptionRaised(UniversalBaseModel):
    detail: typing.Optional[ExceptionRaisedDetail] = None
    message: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
