# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class FieldBid(UniversalBaseModel):
    confidence: typing.Optional[float] = None
    field_id: typing_extensions.Annotated[str, FieldMetadata(alias="fieldId"), pydantic.Field(alias="fieldId")]
    rationale: typing.Optional[str] = None
    value: typing.Any

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
