# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .text_format import TextFormat


class Field_DateField(UniversalBaseModel):
    type: typing.Literal["DateField"] = "DateField"
    description: typing.Optional[str] = None
    id: str
    label: str
    max: typing.Optional[dt.date] = None
    min: typing.Optional[dt.date] = None
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_DateTime(UniversalBaseModel):
    type: typing.Literal["DateTime"] = "DateTime"
    description: typing.Optional[str] = None
    id: str
    label: str
    max: typing.Optional[dt.datetime] = None
    min: typing.Optional[dt.datetime] = None
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Multiselect(UniversalBaseModel):
    type: typing.Literal["Multiselect"] = "Multiselect"
    description: typing.Optional[str] = None
    id: str
    label: str
    options: typing.List[str]
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Number(UniversalBaseModel):
    type: typing.Literal["Number"] = "Number"
    description: typing.Optional[str] = None
    id: str
    integer_only: typing_extensions.Annotated[
        bool, FieldMetadata(alias="integerOnly"), pydantic.Field(alias="integerOnly")
    ]
    label: str
    max: typing.Optional[float] = None
    min: typing.Optional[float] = None
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Select(UniversalBaseModel):
    type: typing.Literal["Select"] = "Select"
    description: typing.Optional[str] = None
    id: str
    label: str
    options: typing.List[str]
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Slider(UniversalBaseModel):
    type: typing.Literal["Slider"] = "Slider"
    description: typing.Optional[str] = None
    id: str
    label: str
    max: float
    min: float
    required: bool
    step: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Switch(UniversalBaseModel):
    type: typing.Literal["Switch"] = "Switch"
    description: typing.Optional[str] = None
    id: str
    label: str
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Text(UniversalBaseModel):
    type: typing.Literal["Text"] = "Text"
    description: typing.Optional[str] = None
    format: typing.Optional[TextFormat] = None
    id: str
    label: str
    max_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="maxLength"), pydantic.Field(alias="maxLength", default=None)
    ]
    min_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="minLength"), pydantic.Field(alias="minLength", default=None)
    ]
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_TextArea(UniversalBaseModel):
    type: typing.Literal["TextArea"] = "TextArea"
    description: typing.Optional[str] = None
    id: str
    label: str
    max_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="maxLength"), pydantic.Field(alias="maxLength", default=None)
    ]
    min_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="minLength"), pydantic.Field(alias="minLength", default=None)
    ]
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class Field_Time(UniversalBaseModel):
    type: typing.Literal["Time"] = "Time"
    description: typing.Optional[str] = None
    id: str
    label: str
    max: typing.Optional[str] = None
    min: typing.Optional[str] = None
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


Field = typing_extensions.Annotated[
    typing.Union[
        Field_DateField,
        Field_DateTime,
        Field_Multiselect,
        Field_Number,
        Field_Select,
        Field_Slider,
        Field_Switch,
        Field_Text,
        Field_TextArea,
        Field_Time,
    ],
    pydantic.Field(discriminator="type"),
]
