# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .document import Document


class MetadataPatch(UniversalBaseModel):
    empty: typing.Optional[bool] = None
    set_: typing_extensions.Annotated[
        typing.Optional[Document], FieldMetadata(alias="set"), pydantic.Field(alias="set", default=None)
    ]
    set_once: typing_extensions.Annotated[
        typing.Optional[Document], FieldMetadata(alias="setOnce"), pydantic.Field(alias="setOnce", default=None)
    ]
    unset: typing.Optional[typing.List[str]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
