# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Number(UniversalBaseModel):
    description: typing.Optional[str] = None
    id: str
    integer_only: typing_extensions.Annotated[
        bool, FieldMetadata(alias="integerOnly"), pydantic.Field(alias="integerOnly")
    ]
    label: str
    max: typing.Optional[float] = None
    min: typing.Optional[float] = None
    required: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
