# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .open_request_dto_event_type import OpenRequestDtoEventType


class OpenRequestDto(UniversalBaseModel):
    event_type: typing_extensions.Annotated[
        OpenRequestDtoEventType, FieldMetadata(alias="eventType"), pydantic.Field(alias="eventType")
    ]
    request_id: typing_extensions.Annotated[str, FieldMetadata(alias="requestId"), pydantic.Field(alias="requestId")]
    requested_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="requestedAt"), pydantic.Field(alias="requestedAt")
    ]
    summary: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
