# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .open_request_dto_event_type import OpenRequestDtoEventType


class OpenRequestDto(UniversalBaseModel):
    event_type: typing_extensions.Annotated[
        typing.Optional[OpenRequestDtoEventType], FieldMetadata(alias="eventType"), pydantic.Field(alias="eventType")
    ] = None
    request_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="requestId"), pydantic.Field(alias="requestId")
    ] = None
    requested_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="requestedAt"), pydantic.Field(alias="requestedAt")
    ] = None
    summary: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
