# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .outcome_type import OutcomeType


class Outcome(UniversalBaseModel):
    note: typing.Optional[str] = None
    reason_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="reasonCode"), pydantic.Field(alias="reasonCode", default=None)
    ]
    type: OutcomeType

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
