# This file was auto-generated by Fern from our API Definition.

import typing

OutcomeType = typing.Union[
    typing.Literal["APPROVE", "REJECT", "EDIT_AND_APPROVE", "ESCALATE", "REQUEST_MORE_INFO"], typing.Any
]
