# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .action_detail import ActionDetail
from .approval_recommendation import ApprovalRecommendation
from .attachment import Attachment
from .authority_snapshot import AuthoritySnapshot
from .elicitation_requested_fields_item import ElicitationRequestedFieldsItem
from .exception_raised_detail import ExceptionRaisedDetail
from .field_bid import FieldBid
from .metadata_patch import MetadataPatch
from .outcome import Outcome


class Payload_Action(UniversalBaseModel):
    type: typing.Literal["Action"] = "Action"
    add_attachments: typing_extensions.Annotated[
        typing.Optional[typing.List[Attachment]],
        FieldMetadata(alias="addAttachments"),
        pydantic.Field(alias="addAttachments"),
    ] = None
    description: str
    detail: typing.Optional[ActionDetail] = None
    metadata_patch: typing_extensions.Annotated[
        MetadataPatch, FieldMetadata(alias="metadataPatch"), pydantic.Field(alias="metadataPatch")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_ApprovalDecided(UniversalBaseModel):
    type: typing.Literal["ApprovalDecided"] = "ApprovalDecided"
    authority: typing.Optional[AuthoritySnapshot] = None
    outcome: Outcome
    recommendation_snapshot: typing_extensions.Annotated[
        typing.Optional[ApprovalRecommendation],
        FieldMetadata(alias="recommendationSnapshot"),
        pydantic.Field(alias="recommendationSnapshot"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_ApprovalRequested(UniversalBaseModel):
    type: typing.Literal["ApprovalRequested"] = "ApprovalRequested"
    attachments: typing.Optional[typing.List[str]] = None
    key_value_context: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="keyValueContext"),
        pydantic.Field(alias="keyValueContext"),
    ] = None
    recommendation: typing.Optional[ApprovalRecommendation] = None
    summary: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_Assignment(UniversalBaseModel):
    type: typing.Literal["Assignment"] = "Assignment"
    assignee_id: typing_extensions.Annotated[str, FieldMetadata(alias="assigneeId"), pydantic.Field(alias="assigneeId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_ElicitationProvided(UniversalBaseModel):
    type: typing.Literal["ElicitationProvided"] = "ElicitationProvided"
    answered_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="answeredBy"), pydantic.Field(alias="answeredBy")
    ] = None
    answers: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_ElicitationRequested(UniversalBaseModel):
    type: typing.Literal["ElicitationRequested"] = "ElicitationRequested"
    attachments: typing.Optional[typing.List[str]] = None
    fields: typing.Optional[typing.List[ElicitationRequestedFieldsItem]] = None
    key_value_context: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="keyValueContext"),
        pydantic.Field(alias="keyValueContext"),
    ] = None
    recommendation: typing.Optional[typing.List[FieldBid]] = None
    summary: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_ExceptionRaised(UniversalBaseModel):
    type: typing.Literal["ExceptionRaised"] = "ExceptionRaised"
    detail: typing.Optional[ExceptionRaisedDetail] = None
    message: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_Note(UniversalBaseModel):
    type: typing.Literal["Note"] = "Note"
    message: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_TaskClosed(UniversalBaseModel):
    type: typing.Literal["TaskClosed"] = "TaskClosed"
    terminal_state: typing_extensions.Annotated[
        str, FieldMetadata(alias="terminalState"), pydantic.Field(alias="terminalState")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_TaskCreated(UniversalBaseModel):
    type: typing.Literal["TaskCreated"] = "TaskCreated"
    initial_state: typing_extensions.Annotated[
        str, FieldMetadata(alias="initialState"), pydantic.Field(alias="initialState")
    ]
    metadata_patch: typing_extensions.Annotated[
        MetadataPatch, FieldMetadata(alias="metadataPatch"), pydantic.Field(alias="metadataPatch")
    ]
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Payload_Timeout(UniversalBaseModel):
    type: typing.Literal["Timeout"] = "Timeout"
    state: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Payload = typing_extensions.Annotated[
    typing.Union[
        Payload_Action,
        Payload_ApprovalDecided,
        Payload_ApprovalRequested,
        Payload_Assignment,
        Payload_ElicitationProvided,
        Payload_ElicitationRequested,
        Payload_ExceptionRaised,
        Payload_Note,
        Payload_TaskClosed,
        Payload_TaskCreated,
        Payload_Timeout,
    ],
    pydantic.Field(discriminator="type"),
]
