# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .project_response import ProjectResponse


class ProjectListResponse(UniversalBaseModel):
    items: typing.Optional[typing.List[ProjectResponse]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
