# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .steps import Steps


class ProjectResponse(UniversalBaseModel):
    id: str
    name: str = pydantic.Field()
    """
    Human-readable display name
    """

    project_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectName"),
        pydantic.Field(alias="projectName", description="The slug — reference the project by this on ingest"),
    ]
    steps: Steps

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
