# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class Slider(UniversalBaseModel):
    description: typing.Optional[str] = None
    id: str
    label: str
    max: float
    min: float
    required: bool
    step: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
