# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .step_owner import StepOwner


class Step(UniversalBaseModel):
    exits: typing.Optional[typing.List[str]] = None
    name: str
    owner: StepOwner

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
