# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .document import Document
from .step import Step


class Steps(UniversalBaseModel):
    initial_step: typing_extensions.Annotated[
        str, FieldMetadata(alias="initialStep"), pydantic.Field(alias="initialStep")
    ]
    step_schemas: typing_extensions.Annotated[
        typing.Optional[Document], FieldMetadata(alias="stepSchemas"), pydantic.Field(alias="stepSchemas", default=None)
    ]
    steps: typing.List[Step]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
