# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .task_response import TaskResponse


class TaskListResponse(UniversalBaseModel):
    items: typing.Optional[typing.List[TaskResponse]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
