# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .open_request_dto import OpenRequestDto
from .task_response import TaskResponse


class TaskDetailResponse(UniversalBaseModel):
    open_requests: typing_extensions.Annotated[
        typing.Optional[typing.List[OpenRequestDto]],
        FieldMetadata(alias="openRequests"),
        pydantic.Field(alias="openRequests"),
    ] = None
    task: typing.Optional[TaskResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
