# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .metadata_patch import MetadataPatch


class TaskCreated(UniversalBaseModel):
    initial_state: typing_extensions.Annotated[
        str, FieldMetadata(alias="initialState"), pydantic.Field(alias="initialState")
    ]
    metadata_patch: typing_extensions.Annotated[
        MetadataPatch, FieldMetadata(alias="metadataPatch"), pydantic.Field(alias="metadataPatch")
    ]
    name: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
