# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .attachment import Attachment
from .task_response_status import TaskResponseStatus


class TaskResponse(UniversalBaseModel):
    attachments: typing.Optional[typing.List[Attachment]] = None
    current_step: typing_extensions.Annotated[
        str, FieldMetadata(alias="currentStep"), pydantic.Field(alias="currentStep")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    id: str
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    name: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId"), pydantic.Field(alias="projectId")]
    status: TaskResponseStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
