# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .open_request_dto import OpenRequestDto
from .task_response import TaskResponse


class TaskDetailResponse(UniversalBaseModel):
    open_requests: typing_extensions.Annotated[
        typing.Optional[typing.List[OpenRequestDto]],
        FieldMetadata(alias="openRequests"),
        pydantic.Field(alias="openRequests", default=None),
    ]
    task: TaskResponse

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
