# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .event_row import EventRow


class TaskEventsResponse(UniversalBaseModel):
    items: typing.Optional[typing.List[EventRow]] = None
    next_cursor: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="nextCursor"), pydantic.Field(alias="nextCursor", default=None)
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
