# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .text_format import TextFormat


class Text(UniversalBaseModel):
    description: typing.Optional[str] = None
    format: typing.Optional[TextFormat] = None
    id: str
    label: str
    max_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="maxLength"), pydantic.Field(alias="maxLength", default=None)
    ]
    min_length: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="minLength"), pydantic.Field(alias="minLength", default=None)
    ]
    required: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
