# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .upload_ref_status import UploadRefStatus


class UploadRef(UniversalBaseModel):
    id: str
    status: UploadRefStatus

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
