# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.date_field import DateField
from ...types.date_time import DateTime
from ...types.multiselect import Multiselect
from ...types.number import Number
from ...types.select import Select
from ...types.slider import Slider
from ...types.switch import Switch
from ...types.text import Text
from ...types.text_area import TextArea
from ...types.time import Time

CreateElicitationRequestFieldsItem = typing.Union[
    DateField, DateTime, Multiselect, Number, Select, Slider, Switch, Text, TextArea, Time
]
