# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import PumpUpEnvironment

if typing.TYPE_CHECKING:
    from .approvals.client import ApprovalsClient, AsyncApprovalsClient
    from .elicitations.client import AsyncElicitationsClient, ElicitationsClient
    from .events.client import AsyncEventsClient, EventsClient
    from .projects.client import AsyncProjectsClient, ProjectsClient
    from .tasks.client import AsyncTasksClient, TasksClient
    from .uploads.client import AsyncUploadsClient, UploadsClient


class PumpUp:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PumpUpEnvironment
        The environment to use for requests from the client. from .environment import PumpUpEnvironment



        Defaults to PumpUpEnvironment.DEFAULT



    version : str
    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from pumpup import PumpUp

    client = PumpUp(
        "0",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PumpUpEnvironment = PumpUpEnvironment.DEFAULT,
        version: str = "0",
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PUMPUP_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting PUMPUP_API_KEY"
            )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            version=version,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._events: typing.Optional[EventsClient] = None
        self._approvals: typing.Optional[ApprovalsClient] = None
        self._elicitations: typing.Optional[ElicitationsClient] = None
        self._projects: typing.Optional[ProjectsClient] = None
        self._tasks: typing.Optional[TasksClient] = None
        self._uploads: typing.Optional[UploadsClient] = None

    @property
    def events(self):
        if self._events is None:
            from .events.client import EventsClient  # noqa: E402

            self._events = EventsClient(client_wrapper=self._client_wrapper)
        return self._events

    @property
    def approvals(self):
        if self._approvals is None:
            from .approvals.client import ApprovalsClient  # noqa: E402

            self._approvals = ApprovalsClient(client_wrapper=self._client_wrapper)
        return self._approvals

    @property
    def elicitations(self):
        if self._elicitations is None:
            from .elicitations.client import ElicitationsClient  # noqa: E402

            self._elicitations = ElicitationsClient(client_wrapper=self._client_wrapper)
        return self._elicitations

    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import ProjectsClient  # noqa: E402

            self._projects = ProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects

    @property
    def tasks(self):
        if self._tasks is None:
            from .tasks.client import TasksClient  # noqa: E402

            self._tasks = TasksClient(client_wrapper=self._client_wrapper)
        return self._tasks

    @property
    def uploads(self):
        if self._uploads is None:
            from .uploads.client import UploadsClient  # noqa: E402

            self._uploads = UploadsClient(client_wrapper=self._client_wrapper)
        return self._uploads


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncPumpUp:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PumpUpEnvironment
        The environment to use for requests from the client. from .environment import PumpUpEnvironment



        Defaults to PumpUpEnvironment.DEFAULT



    version : str
    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from pumpup import AsyncPumpUp

    client = AsyncPumpUp(
        "0",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PumpUpEnvironment = PumpUpEnvironment.DEFAULT,
        version: str = "0",
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PUMPUP_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting PUMPUP_API_KEY"
            )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            version=version,
            api_key=api_key,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._events: typing.Optional[AsyncEventsClient] = None
        self._approvals: typing.Optional[AsyncApprovalsClient] = None
        self._elicitations: typing.Optional[AsyncElicitationsClient] = None
        self._projects: typing.Optional[AsyncProjectsClient] = None
        self._tasks: typing.Optional[AsyncTasksClient] = None
        self._uploads: typing.Optional[AsyncUploadsClient] = None

    @property
    def events(self):
        if self._events is None:
            from .events.client import AsyncEventsClient  # noqa: E402

            self._events = AsyncEventsClient(client_wrapper=self._client_wrapper)
        return self._events

    @property
    def approvals(self):
        if self._approvals is None:
            from .approvals.client import AsyncApprovalsClient  # noqa: E402

            self._approvals = AsyncApprovalsClient(client_wrapper=self._client_wrapper)
        return self._approvals

    @property
    def elicitations(self):
        if self._elicitations is None:
            from .elicitations.client import AsyncElicitationsClient  # noqa: E402

            self._elicitations = AsyncElicitationsClient(client_wrapper=self._client_wrapper)
        return self._elicitations

    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import AsyncProjectsClient  # noqa: E402

            self._projects = AsyncProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects

    @property
    def tasks(self):
        if self._tasks is None:
            from .tasks.client import AsyncTasksClient  # noqa: E402

            self._tasks = AsyncTasksClient(client_wrapper=self._client_wrapper)
        return self._tasks

    @property
    def uploads(self):
        if self._uploads is None:
            from .uploads.client import AsyncUploadsClient  # noqa: E402

            self._uploads = AsyncUploadsClient(client_wrapper=self._client_wrapper)
        return self._uploads


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: PumpUpEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
