# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.approval_recommendation import ApprovalRecommendation
from ..types.approval_result import ApprovalResult
from ..types.attachment import Attachment
from ..types.event_response import EventResponse
from ..types.metadata_patch_dto import MetadataPatchDto
from ..types.object_id import ObjectId
from .raw_client import AsyncRawApprovalsClient, RawApprovalsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ApprovalsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApprovalsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApprovalsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApprovalsClient
        """
        return self._raw_client

    def create(
        self,
        *,
        idempotency_key: str,
        project_name: str,
        summary: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        attachments: typing.Optional[typing.Sequence[ObjectId]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        recommendation: typing.Optional[ApprovalRecommendation] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the decision.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        project_name : str
            Slug of an existing project (create it ahead of time)

        summary : str
            Human-readable summary of the action needing approval

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        attachments : typing.Optional[typing.Sequence[ObjectId]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]
            Optional link to the agent author's observability trace

        key_value_context : typing.Optional[typing.Dict[str, str]]
            Display context as a plain key→value object (order/dup-keys are the client's concern)

        metadata_patch : typing.Optional[MetadataPatchDto]

        recommendation : typing.Optional[ApprovalRecommendation]

        task_id : typing.Optional[str]
            Target task; omit to use the project's singleton task

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.approvals.create(
            idempotency_key="Idempotency-Key",
            project_name="claims_refund_v1",
            summary="Refund $240 on claim C-1029",
        )
        """
        _response = self._raw_client.create(
            idempotency_key=idempotency_key,
            project_name=project_name,
            summary=summary,
            add_attachments=add_attachments,
            attachments=attachments,
            external_trace_id=external_trace_id,
            key_value_context=key_value_context,
            metadata_patch=metadata_patch,
            recommendation=recommendation,
            task_id=task_id,
            request_options=request_options,
        )
        return _response.data

    def get_result(self, id: ObjectId, *, request_options: typing.Optional[RequestOptions] = None) -> ApprovalResult:
        """
        200 with the outcome once a human has decided; 204 while still pending.

        Parameters
        ----------
        id : ObjectId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApprovalResult
            OK

        Examples
        --------
        from pumpup import PumpUp

        client = PumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )
        client.approvals.get_result(
            id="id",
        )
        """
        _response = self._raw_client.get_result(id, request_options=request_options)
        return _response.data


class AsyncApprovalsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApprovalsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApprovalsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApprovalsClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        idempotency_key: str,
        project_name: str,
        summary: str,
        add_attachments: typing.Optional[typing.Sequence[Attachment]] = OMIT,
        attachments: typing.Optional[typing.Sequence[ObjectId]] = OMIT,
        external_trace_id: typing.Optional[str] = OMIT,
        key_value_context: typing.Optional[typing.Dict[str, str]] = OMIT,
        metadata_patch: typing.Optional[MetadataPatchDto] = OMIT,
        recommendation: typing.Optional[ApprovalRecommendation] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns immediately with an event_id; poll the result endpoint by it for the decision.

        Parameters
        ----------
        idempotency_key : str
            Idempotency key; duplicate submissions return the original event.

        project_name : str
            Slug of an existing project (create it ahead of time)

        summary : str
            Human-readable summary of the action needing approval

        add_attachments : typing.Optional[typing.Sequence[Attachment]]
            Files to attach to the task — upload id + display name (each id from POST /uploads)

        attachments : typing.Optional[typing.Sequence[ObjectId]]
            Upload ids of attached files to render for this request (must already be attached to the task)

        external_trace_id : typing.Optional[str]
            Optional link to the agent author's observability trace

        key_value_context : typing.Optional[typing.Dict[str, str]]
            Display context as a plain key→value object (order/dup-keys are the client's concern)

        metadata_patch : typing.Optional[MetadataPatchDto]

        recommendation : typing.Optional[ApprovalRecommendation]

        task_id : typing.Optional[str]
            Target task; omit to use the project's singleton task

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Created

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.approvals.create(
                idempotency_key="Idempotency-Key",
                project_name="claims_refund_v1",
                summary="Refund $240 on claim C-1029",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            idempotency_key=idempotency_key,
            project_name=project_name,
            summary=summary,
            add_attachments=add_attachments,
            attachments=attachments,
            external_trace_id=external_trace_id,
            key_value_context=key_value_context,
            metadata_patch=metadata_patch,
            recommendation=recommendation,
            task_id=task_id,
            request_options=request_options,
        )
        return _response.data

    async def get_result(
        self, id: ObjectId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApprovalResult:
        """
        200 with the outcome once a human has decided; 204 while still pending.

        Parameters
        ----------
        id : ObjectId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApprovalResult
            OK

        Examples
        --------
        import asyncio

        from pumpup import AsyncPumpUp

        client = AsyncPumpUp(
            "0",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.approvals.get_result(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_result(id, request_options=request_options)
        return _response.data
